In [1]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency, chi2

In [ ]:
# Chi-Square Formula
χ² = Σ [(Observed - Expected)² / Expected]

Where:
- Observed = Actual data
- Expected = Calculated assuming no relationship

This formula measures how much the observed data deviates from expected data.

In [ ]:
#1. Hypotheses
- Null Hypothesis (H0):  
  There is no significant difference between device type and customer satisfaction.

- Alternative Hypothesis (H1):  
  There is a significant difference between device type and customer satisfaction.

In [2]:
# Observed Data(given)
data = np.array([
    [50, 70],   # Very Satisfied
    [80, 100],  # Satisfied
    [60, 90],   # Neutral
    [30, 50],   # Unsatisfied
    [20, 50]    # Very Unsatisfied
])

# Converting to DataFrame
df = pd.DataFrame(data, 
                  columns=["Smart Thermostat", "Smart Light"],
                  index=["Very Satisfied", "Satisfied", "Neutral", "Unsatisfied", "Very Unsatisfied"])
df

                  Smart Thermostat  Smart Light
Very Satisfied                  50           70
Satisfied                       80          100
Neutral                         60           90
Unsatisfied                     30           50
Very Unsatisfied                20           50

In [3]:
#2. Chi-square statistics
chi2_stat, p_value, dof, expected = chi2_contingency(data)

print("Chi-Square Statistic:", chi2_stat)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)

Chi-Square Statistic: 5.638227513227513
P-value: 0.22784371130697179
Degrees of Freedom: 4

In [4]:
#expected frequencies
expected_df = pd.DataFrame(expected, 
                           columns=["Smart Thermostat", "Smart Light"],
                           index=df.index)

print("Expected Frequencies:\n")
expected_df

Expected Frequencies:

                  Smart Thermostat  Smart Light
Very Satisfied                48.0         72.0
Satisfied                     72.0        108.0
Neutral                       60.0         90.0
Unsatisfied                   32.0         48.0
Very Unsatisfied              28.0         42.0

In [5]:
#3. Critical Value
alpha = 0.05

critical_value = chi2.ppf(1 - alpha, dof)
print("Critical Value:", critical_value)

Critical Value: 9.487729036781154

In [8]:
#4. Decision
if chi2_stat > critical_value:
    print("Reject Null Hypothesis (H0)")
else:
    print("Fail to Reject Null Hypothesis (H0)") #This means H0 is accepted and H1 is rejected.

Fail to Reject Null Hypothesis (H₀)

In [ ]:
Interpretation
Ho is accepted and H1 is rejected.
Thus there is no significant difference between device type and customer satisfaction to
suggest a relationship between them.
Any differences observed in satisfaction levels may be due to random variation ranther 
than actual effect.

In [ ]:
Conclusion
Chi square test is the one of the simplest method mostly used in non parametric test in statistical world.
Customer satisfaction is independent of the type of smart device purchased.